<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\EducationQuestions.Contracts\EducationQuestions.Contracts.csproj" />
      <ProjectReference Include="..\EducationQuestions.Domain\EducationQuestions.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.9" />
      <PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.556">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen.ConventionalRouting" Version="4.3.0" />
      <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen.ConventionalRoutingWithStrongName" Version="3.0.1.9" />
    </ItemGroup>

</Project>
